Changing max population checks to match world population
ihmeuw/vivarium_inputs pull request #282
Opened 2022-01-21 23:32 UTC by albrja

Changed max population upper bound checks to match world population.

Category: feature
JIRA issue: [MIC-2828](https://jira.ihme.washington.edu/browse/MIC-2828)

Verification and Testing
Ran make_artifacts and successfully created artifacts for Sub-Saharan Africa and South Asia.

2022-01-21 23:49 UTC, hussain-jafari approved these changes

2022-01-21 23:51 UTC, collijk requested changes
The goal in the check here is to provide the **smallest reasonable upper bound** for validation checks.  

In raw validation, you're checking on a data set that is age-specific, but not sex-specific (inferring from the comment on the original value).  That means you want to use an upper bound that is at least as big as the largest single age-group population for the global location id (say, round up to the nearest million people).  In the sim validation context, you're checking a dataset that is age- and sex-specific, so you want to use something a little larger (again, round up to the nearest million) than the largest single age/sex-group population.  

Using the total world population gives you an upper bound that is 10-40x (estimating) larger than the largest thing you should be checking, which means we'd say a population 10x too high would be fine with us.

2022-01-21 23:51 UTC, collijk commented on src/vivarium_inputs/validation/raw.py
> -MAX_POP = 145_000_000  # pop data includes both sexes combined at this point
You should be changing this value to the maximum population in a single age group for location id 1.

2022-01-21 23:51 UTC, collijk commented on src/vivarium_inputs/validation/sim.py
> -VALID_POPULATION_RANGE = (0, 75_000_000)
This should change to the maximum population for a single age _and_ sex group for location id 1.

2022-01-21 23:54 UTC, mattkappel commented on src/vivarium_inputs/validation/sim.py
> -VALID_POPULATION_RANGE = (0, 75_000_000)
Ok, this is different from what the bug (I) said based on our discussion last week. We can make this change.

2022-01-21 23:54 UTC, mattkappel commented on src/vivarium_inputs/validation/sim.py
> -VALID_POPULATION_RANGE = (0, 75_000_000)
And we do want these checks to use different numbers, too?

2022-01-22 00:25 UTC, mattkappel approved these changes

2022-01-22 00:29 UTC, merged