Fix bug with estimation years
ihmeuw/vivarium_inputs pull request #351
Opened 2024-06-26 18:12 UTC by hussain-jafari

## Fix bug with estimation years

### Description
- *Category*: bugfix
- *JIRA issue*: none

### Changes and notes
Corrected validation of the years parameter.

### Testing
Have not tested this.

2024-06-26 18:14 UTC, rmudambi approved these changes
Looks good. Make sure to squash the commits

2024-06-26 20:34 UTC, albrja approved these changes

2024-07-02 00:15 UTC, rmudambi requested changes

2024-07-02 00:15 UTC, rmudambi commented on src/vivarium_inputs/extract.py
> +                all_data = []
You shouldn't be defining `all_data` inside this loop.

2024-07-02 00:15 UTC, rmudambi commented on src/vivarium_inputs/extract.py
> +            for year in year_id:
This can be done in a vectorized fashion using `pd.merge`:
```python
import pandas as pd

# Assuming 'data' is your original DataFrame
data = pd.DataFrame(...)  # Your data initialization

# Create a DataFrame from your year_ids
year_df = pd.DataFrame({'year_id': year_id})

# Perform a cross join by creating a temporary key to merge on
data['key'] = 1
year_df['key'] = 1

# Merge to get the Cartesian product, then drop the key column
expanded_data = pd.merge(data, year_df, on='key').drop('key', axis=1)
```

I got this using ChatIHME and I encourage you to do the same if you find yourself performing operations like this in python loops.

2024-07-02 16:28 UTC, hussain-jafari commented on src/vivarium_inputs/extract.py
> +                all_data = []
Yeah wow I need to see how this passed testing.

2024-07-02 20:05 UTC, rmudambi approved these changes

2024-07-02 20:14 UTC, merged