Sbachmei/mic 5407 5442/add cause and sequela like tests
ihmeuw/vivarium_inputs pull request #374
Opened 2024-10-18 15:36 UTC by stevebachmeier

## Add tests against Cause and Sequela data retrieval

### Description

- *Category*:  test
- *JIRA issue*: https://jira.ihme.washington.edu/browse/MIC-5407

### Changes and notes
 
this implements a few tests for Cause and one for Sequela data
retrieval. There are instances where I can't get data (likely due to my
ignorance) and so I'm adding FIXME skips to them to fix in the future.

Following PRs will implement the other types (Covariate, RiskFactor, etc)
as well as mocked versions.

### Testing

2024-10-18 16:38 UTC, hussain-jafari commented on src/vivarium_inputs/validation/raw.py
> +    # The value columns are irrelevant of the data_type in this case
Should this be "the value columns of the data_type"? It's a bit confusing to parse like this

2024-10-18 16:41 UTC, hussain-jafari commented on tests/e2e/test_get_measure.py
> +    # NOTE: 'raw_incident_rate' and 'deaths' should not be called directly from `get_measure()`
nit: raw_incidence_rate

2024-10-18 16:44 UTC, rmudambi requested changes

2024-10-18 16:44 UTC, rmudambi commented on src/vivarium_inputs/core.py
> +    data = get_data(entity, "raw_incidence_rate", location_id, years, data_type.type)
In this case (and possibly every case in this file), the data type we already have is exactly the same as the one we want for raw incidence rate even though they have different measures. If we need a different DataType, we could create it here and just pass it to `get_data()`

We don't really use the measure. I think it's simpler and more elegant to modify the `init` of `DataType` like this, and have a docstring that communicates the measures for which you want to force the value column (the parameter name could probably be improved):

```python
def __init__(self, data_type: str | list[str], force_value_column: bool = False) -> None:
    ...
```

2024-10-18 16:44 UTC, rmudambi commented on src/vivarium_inputs/core.py
> +            data = utilities.normalize(data, DRAW_COLUMNS)
You shouldn't need to change this? Especially if you make the change I suggested above.

2024-10-18 16:44 UTC, rmudambi commented on src/vivarium_inputs/validation/raw.py
> +            DRAW_COLUMNS,
Why is this not `value_columns`? Same question everywhere you are doing this in `checkXRestrictions()`.

2024-10-18 16:44 UTC, rmudambi commented on src/vivarium_inputs/validation/raw.py
> +    value_columns: list[str],
If the value_columns are never used, why are we passing them to this function?

2024-10-18 16:44 UTC, rmudambi commented on tests/e2e/test_get_measure.py
> +@pytest.fixture(autouse=True)
This is identical to the `no_cache` fixture in GBD Access, right? Is this something we should pull out and put in VTU?

2024-10-18 16:55 UTC, hussain-jafari commented on tests/e2e/test_get_measure.py
> +    assert all(data >= 0)
This isn't always true - for example, PAFs can be negative like for FPG. I asked CC about this and they said "Hi Hussain Jafari this is expected in some risks - for example some risks may have a protective effect and reduce the chance of an outcome occurring." I'm not sure if it happens for any measure other than PAFs though. I believe we are capping our PAFs to be greater than -1 though.

2024-10-18 16:57 UTC, hussain-jafari commented on tests/e2e/test_get_measure.py
> +    assert all(data >= 0)
I think it's only not true for PAFs though

2024-10-18 21:47 UTC, stevebachmeier commented on src/vivarium_inputs/validation/raw.py
> +            DRAW_COLUMNS,
As discussed, I was having issues since value_columns isn't implemented everywhere. I'll put it back and try again, though.

2024-10-18 21:50 UTC, stevebachmeier commented on src/vivarium_inputs/validation/raw.py
> +    value_columns: list[str],
Because these validation functions get called off of a mapper like `validator["measure"](..., value_columns)`

2024-10-18 21:51 UTC, stevebachmeier commented on src/vivarium_inputs/validation/raw.py
> +    # The value columns are irrelevant of the data_type in this case
Most "value_columns" are very specifically defined by the `data_type`, i.e. a data type of "draws" means `value_columns` == ['draw_*'] and a data_type of "means" means `value_columns` == ['val']. But here, I'm trying to convey that regardless of what `data_type` is, we are using custom value_columns.

2024-10-18 21:52 UTC, stevebachmeier commented on tests/e2e/test_get_measure.py
> +@pytest.fixture(autouse=True)
Yeah I was thinking about that when we were discussing future projects. We could. It would only really be used by these two repos I think but at least would be centralized.

2024-10-18 21:54 UTC, stevebachmeier commented on tests/e2e/test_get_measure.py
> +    assert all(data >= 0)
Hmm, good call. I think I'll leave it for now and re-address when something breaks.

2024-10-18 23:03 UTC, rmudambi approved these changes

2024-10-18 23:03 UTC, rmudambi commented on tests/e2e/test_get_measure.py
> +@pytest.fixture(autouse=True)
Can you create a JIRA ticket to do this?

2024-10-18 23:18 UTC, hussain-jafari commented on src/vivarium_inputs/validation/raw.py
> +    # The value columns are irrelevant of the data_type in this case
Ah maybe something like "the value columns do not depend on the data_type in this case"?

2024-10-18 23:19 UTC, hussain-jafari approved these changes

2024-10-21 15:59 UTC, stevebachmeier commented on src/vivarium_inputs/utilities.py
> +        also be a list of values to get multiple data types."""
"or None if you want to specifically use the columns passed in." was my attempt at that. I'll convert to a list to hopefully make it more clear.

I also hope this clarifies that my intent was that a None data type won't go away when means is fully implemented. It's actually reserved more for when you're passing in value_cols, i.e. the type of data really isn't "means" or "draws".

Clearly there's a refactor in order but I haven't thought yet about how to do it

2024-10-21 17:39 UTC, rmudambi commented on src/vivarium_inputs/utilities.py
> +        """
I still think `value_cols` (and supporting None as a `data_type` will go away once `get_means` is implemented. Maybe we should talk if you disagree.

2024-10-21 18:49 UTC, patricktnast commented on src/vivarium_inputs/validation/raw.py
> +    entity: Union[Cause, Sequela],
nit: change to Cause | Sequela

2024-10-21 18:49 UTC, patricktnast commented on src/vivarium_inputs/validation/sim.py
> +    data_type: DataType,
It looks like there are several calls to `validate_for_simulation` that don't include a data_type argument.

2024-10-21 18:49 UTC, patricktnast commented on src/vivarium_inputs/utilities.py
>          self.type = data_type
i find this (and subsequent gbd calls arguments given as data_type.type) slightly annoying, but i dont know that theres a more legible alternative.

2024-10-21 18:49 UTC, patricktnast commented on tests/unit/test_utilities.py
> +        _data_type = utilities.DataType(data_type, value_cols)
couldn't you just do `utilities.DataType(data_type, value_cols)` here?

2024-10-21 19:59 UTC, albrja approved these changes

2024-10-22 15:22 UTC, stevebachmeier commented on src/vivarium_inputs/validation/sim.py
> +    data_type: DataType,
They just aren't implemented yet. We runtime error higher up the call stack if you pass in anything but draws.

2024-10-22 15:23 UTC, stevebachmeier commented on src/vivarium_inputs/utilities.py
>          self.type = data_type
You and me both, brother.

2024-10-22 15:24 UTC, stevebachmeier commented on tests/unit/test_utilities.py
> +        _data_type = utilities.DataType(data_type, value_cols)
As opposed to assigning the return to something? Yeah, that would work. We (and obviously I) are not totally consistent in tests with this if we're not actually doing anything with the return

2024-10-22 15:33 UTC, merged